//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RichmondDay
{
    using System;
    using System.Collections.Generic;
    
    public partial class MOCK_DATA
    {
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string email { get; set; }
        public System.Guid emp_id { get; set; }
    }
}
